### ISSUE TITLE
Review enclosure design

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Rev_F_Hardware#9]
Noticed a couple of issues with the new enclosure (recvd Sept 24, 2024).
- [x] Heat sink insert needs thicker boss
- [ ] ~Square light pipe hard to press in (but goes in well after initial push)~  Design matches specs.  Leave as-is for now.
- [x] Upload revised design and STEP, STLs.

**Comment by eyuan-creare** [comment]
Fixed the missing boss reinforcement.  I didn't mirror the feature.

![image](https://github.com/user-attachments/assets/d5fbbc8e-077e-4024-89b7-10ace8a0a5a8)

**Comment by eyuan-creare** [comment]
Charging LED: BIVAR PLPQ2-188-FF
- Requires panel cutout of 0.080in sq with 0.008in radius.
![image](https://github.com/user-attachments/assets/0e49fd14-4247-4b36-840e-cda8eb847dd7)

This matches the existing design:
![image](https://github.com/user-attachments/assets/c28ba06a-441a-4718-b282-bbbc0a53cafd)

Leave as-is for now and see if it is an issue with future prints.
-

**Comment by biomurph** [comment]
@eyuan-creare 
I have not been using a square light pipe in that position. 
The charge LED shines through quite well as it is.

You mention the heat-sink insert, the blue in your rendering is on the screw side of the join, not the thread side?

**Comment by eyuan-creare** [comment]
Yes, my mistake.  The clearance for the screwdriver has a thin wall that blew through.  I've added thickness there.  I will correct the typo in the issue.  Light pipe won't be present for typical production units, correct.

**Comment by eyuan-creare** [comment]
Uploaded new STL's (units: mm), STEP, and PDF of assembly drawing.  Pushed new files to branch and merged with trunk.
